name: LiDARKitDemo
options:
    deploymentTarget:
        iOS: 15.0
    xcodeFlags:
        - "-allowProvisioningUpdates"
targets:
    LiDARKit:
        type: framework
        platform: iOS
        deploymentTarget: "15.0"
        sources:
            - path: ../../Sources/LiDARKit
        settings:
            base:
                SKIP_INSTALL: YES
                BUILD_LIBRARY_FOR_DISTRIBUTION: YES
                GENERATE_INFOPLIST_FILE: YES
                PRODUCT_BUNDLE_IDENTIFIER: "com.timonyang.lidarkit"
                CURRENT_PROJECT_VERSION: 1
                MARKETING_VERSION: 1.0.0
                DEFINES_MODULE: YES
                DYLIB_COMPATIBILITY_VERSION: 1
                DYLIB_CURRENT_VERSION: 1
                DYLIB_INSTALL_NAME_BASE: "@rpath"
                INSTALL_PATH: "@rpath"
                LD_RUNPATH_SEARCH_PATHS:
                    ["@executable_path/Frameworks", "@loader_path/Frameworks"]
                DEVELOPMENT_TEAM: ""
    LiDARKitDemo:
        type: application
        platform: iOS
        sources:
            - LiDARKitDemo
        dependencies:
            - target: LiDARKit
        settings:
            base:
                TARGETED_DEVICE_FAMILY: 1,2
                CODE_SIGN_STYLE: Automatic
                CODE_SIGN_IDENTITY: "Apple Development"
                DEVELOPMENT_TEAM: ""
                PRODUCT_BUNDLE_IDENTIFIER: "com.timonyang.lidarkit.demo"
                PRODUCT_NAME: LiDARKitDemo
                GENERATE_INFOPLIST_FILE: YES
                LD_RUNPATH_SEARCH_PATHS: ["@executable_path/Frameworks"]
        info:
            path: LiDARKitDemo/Info.plist
            properties:
                CFBundleDisplayName: LiDARKit Demo
                UILaunchStoryboardName: ""
                UIApplicationSceneManifest:
                    UIApplicationSupportsMultipleScenes: false
                    UISceneConfigurations:
                        UIWindowSceneSessionRoleApplication:
                            - UISceneConfigurationName: Default Configuration
                              UISceneDelegateClassName: $(PRODUCT_MODULE_NAME).SceneDelegate
                NSCameraUsageDescription: This app needs camera access to capture LiDAR data
                UIRequiredDeviceCapabilities: [armv7, arkit]
                UISupportedInterfaceOrientations:
                    [UIInterfaceOrientationPortrait]
